name: server CI/CD 
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.4
      - name: Install packages
        run: |
         sudo apt-get update && sudo apt-get install git build-essential unzip libssl-dev -y
      
      - name: Install wrk
        run: |
         sudo git clone https://github.com/wg/wrk.git wrk && cd wrk && make

      - name: Install dependencies
        run: poetry install
      - name: Run linter flake8
        run: |
          poetry run flake8 --max-line-length=120
          
      - name: Run server
        run: |
          nohup poetry run python server.py &

      - name: Run wrk
        run: |
         ./wrk -t10 -c10 http://127.0.0.1:8080/