name: server CI/CD 
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.4
      - name: Install dependencies
        run: poetry install
      - name: Run linter flake8
        run: |
          poetry run flake8 --max-line-length=120
          
      - name: Run server
        run: |
          nohup poetry run python server.py &
          
      -name: Build test container
       run: docker build -t benchmark-image -f docker/benchmark.Dockerfile
       
      -name: Run test container
       run: docker run benchmark-image